---
- name: Create a user on remote server
  hosts: all
  become: true
  tasks:
    - name: Create user "john"
      user:
        name: john
        state: present
      register: user_out
    - name: output user
      debug:
        var: user_out
