---
- name: Manage firewall rules
  hosts: all
  become: true
  tasks:
    - name: Allow HTTP service through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled

