---
- name: Install Apache without condition
  hosts: all
  become: true
  tasks:
    - name: Install Apache directly
      yum:
        name: httpd
        state: present
      ignore_errors: yes  # Optional: avoid playbook failure

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: true

