- name: Install packages based on OS
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install packages on Debian/Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - curl
        - vim
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on RedHat/CentOS
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - vim
      when: ansible_facts['os_family'] == "RedHat"

