---
- name: Install Apache on CentOS 7 (RedHat family)
  hosts: all
  become: true
  tasks:
    - name: Install Apache if OS is RedHat
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts['os_family'] == 'RedHat'

