- name: Install a package on target host
  hosts: all
  become: yes
  vars:
    package_name: "htop"   # play-scope variable (default)

  tasks:
    - name: Install the desired package
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
      register: std_outt
    - name: print out_put
      debug:
        var: std_outt
