---
- name: Print host-scoped variables
  hosts: webserver
  gather_facts: false

  tasks:
    - name: Print server name
      debug:
        msg: "Server Name: {{ name }}"

    - name: Print server location
      debug:
        msg: "Location: {{ location }}"

    - name: Print server role
      debug:
        msg: "Role: {{ role }}"

