- name: Copy and run Python script
  hosts: all
  tasks:
    - name: Copy the script to remote
      copy:
        src: hello.py
        dest: /tmp/hello.py
        mode: '0755'

    - name: Execute the script
      shell: python3 /tmp/hello.py

