---
- name: Slurp file content
  hosts: all
  tasks:
    - name: Read a file content
      slurp:
        src: /home/ansible/one.txt
      register: file_content
    - name: Print file content
      debug:
        msg: "{{ file_content.content | b64decode }}"

